version: "2"
linters:
  default: all
  disable:
    # deprecated
    - wsl
    - gomodguard
    # useless
    - tagalign
    - ireturn
    # own style
    - revive
    - noinlineerr
    # temporary disabled
    - cyclop
    - exhaustruct
    - funlen

  settings:
    varnamelen:
      ignore-names:
        - ch
        - id
        - val
        - ok
        - lc
        - db
        - c # c *gin.Context
    depguard:
      rules:
        prevent_bad_architecture:
          list-mode: lax # allow unless explicitely denied
          files:
            - $all
            - "!$test"
          deny:
            - pkg: sourcecraft.dev/organization-shipmonitor/ship-cloud-auth/services/*
              desc: "Should be replaced"
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
    golines:
      max-len: 80
      tab-len: 4
      shorten-comments: true
      reformat-tags: false
      chain-split-dots: true
