version: "2"
linters:
  default: all
  disable:
    - wsl
    - tagalign
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax # allow unless explicitely denied
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
    golines:
      max-len: 100
      tab-len: 4
      shorten-comments: true
      reformat-tags: false
      chain-split-dots: true
      
      
