version: "2"
linters:
  default: all
  disable:
    # deprecated
    - wsl
    - gomodguard
    # useless
    - tagalign
    - ireturn
    # own style
    - revive
    - noinlineerr
    # temporary disabled
    - cyclop
    - exhaustruct
    - funlen

  settings:
    wrapcheck:
      report-internal-errors: true
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .JSON(
        - .NoContent(

    varnamelen:
      ignore-names:
        - ch
        - id
        - val
        - ok
        - lc
        - db
        - in
        - c # c *echo.Context
    depguard:
      rules:
        prevent_repo_in_service:
          list-mode: lax # allow unless explicitely denied
          files:
            - "**/internal/services/*"
          deny:
            - pkg: github.com/ship-monitor/cloud/internal/repository
              desc: Should inverse this dependency
        prevent_service_in_handlers:
          list-mode: lax # allow unless explicitely denied
          files:
            - "**/internal/handlers/*"
          deny:
            - pkg: github.com/ship-monitor/cloud/internal/services
              desc: Should inverse this dependency
        prevent_plain_viper:
          list-mode: lax
          files:
            - $all
            - "!$test"
          deny:
            - pkg: github.com/spf13/viper
              desc: "Should be moved to typed configurations"
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: true
    gofumpt:
      extra-rules: true
    golines:
      max-len: 80
      tab-len: 4
      shorten-comments: true
      reformat-tags: false
      chain-split-dots: true
