volumes:
  orgs_data:
  rabbitmq_data:

networks:
  auth-net:
    driver: bridge

services:
  # AUTH SERVICE
  auth-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@auth-db:5432/postgres?sslmode=disable
      SECURITY_KEY: "your_jwt_security_key_here"
    depends_on:
      - auth-db
      - spice
    networks:
      - auth-net
  # AUTH SERVICE DATABASE
  auth-db:
    networks:
      - auth-net
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # RABBITMQ
  rabbitmq:
    image: rabbitmq:4-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - auth-net
