volumes:
  auth_data:
  rabbitmq_data:

networks:
  auth-net:
    driver: bridge

services:
  # AUTH SERVICE
  auth-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8071:8071"
    environment:
      PORT: 8080
      DATABASE_URL: postgres://katy:postgres@auth-db:5432/auth-db?sslmode=disable
      SECURITY_KEY: "your_jwt_security_key_here"
      SERVICES_CONNECTOR_RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - auth-db
      - rabbitmq
    networks:
      - auth-net
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8080/api/health -f || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 30s
  # AUTH SERVICE DATABASE
  auth-db:
    networks:
      - auth-net
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: katy
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth-db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U katy -d auth-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  # RABBITMQ
  rabbitmq:
    image: rabbitmq:4-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - auth-net
