schema: |-
  definition user {}

  definition organization {
  	relation owner: user
  	relation member: user
  	relation administrator: user
  	permission view = member + owner
  	permission edit = owner + administrator
  	permission delete = owner
  	permission connect_device = owner + administrator
  	permission disconnect_device = owner + administrator
  	relation connected: device
  	permission invite_member = owner + administrator
  	permission delete_member = owner + administrator
  }

  definition device {}
relationships: |-
  // Some example relationships
  organization:org1#member@user:katy
  organization:org1#member@user:oleg
  organization:org2#owner@user:jay
  
assertions:
  assertTrue:
    - organization:org2#view@user:jay
  assertFalse:
    - organization:org2#view@user:katy
    - organization:org2#view@user:oleg
validation: {}
